"""
Mock Image Generation Service - Simulates Stable Diffusion/DALL-E
"""
from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional
from PIL import Image, ImageDraw, ImageFont
import io
import random
import time

app = FastAPI(title="Mock Image Generation Service")

class ImageGenRequest(BaseModel):
    prompt: str
    width: Optional[int] = 1024
    height: Optional[int] = 1024
    steps: Optional[int] = 50
    guidance_scale: Optional[float] = 7.5
    seed: Optional[int] = None

def generate_placeholder_image(prompt: str, width: int, height: int) -> bytes:
    """Generate a placeholder image with the prompt text"""
    
    # Create a gradient background
    img = Image.new('RGB', (width, height), color='#1a1a2e')
    draw = ImageDraw.Draw(img)
    
    # Add gradient effect
    for y in range(height):
        shade = int(26 + (y / height) * 40)
        color = (shade, shade, shade + 20)
        draw.line([(0, y), (width, y)], fill=color)
    
    # Add prompt text (truncated if too long)
    text = prompt[:100] + "..." if len(prompt) > 100 else prompt
    
    # Try to use a font, fallback to default if not available
    try:
        font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 30)
    except:
        font = ImageFont.load_default()
    
    # Calculate text position (centered)
    text_bbox = draw.textbbox((0, 0), text, font=font)
    text_width = text_bbox[2] - text_bbox[0]
    text_height = text_bbox[3] - text_bbox[1]
    
    position = ((width - text_width) // 2, (height - text_height) // 2)
    
    # Draw text with shadow
    shadow_offset = 2
    draw.text((position[0] + shadow_offset, position[1] + shadow_offset), 
              text, fill=(0, 0, 0), font=font)
    draw.text(position, text, fill=(100, 200, 255), font=font)
    
    # Add "Mock Image" watermark
    watermark = "Generated by Mock Service"
    watermark_bbox = draw.textbbox((0, 0), watermark, font=font)
    watermark_width = watermark_bbox[2] - watermark_bbox[0]
    draw.text(((width - watermark_width) // 2, height - 50), 
              watermark, fill=(150, 150, 150), font=font)
    
    # Convert to bytes
    img_byte_arr = io.BytesIO()
    img.save(img_byte_arr, format='PNG')
    img_byte_arr.seek(0)
    return img_byte_arr.getvalue()

@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "mock-image-gen"}

@app.post("/v1/generate")
async def generate_image(request: ImageGenRequest):
    """Mock image generation endpoint"""
    
    if not request.prompt:
        raise HTTPException(status_code=400, detail="Prompt is required")
    
    # Validate dimensions
    if request.width < 256 or request.width > 2048:
        raise HTTPException(status_code=400, detail="Width must be between 256 and 2048")
    if request.height < 256 or request.height > 2048:
        raise HTTPException(status_code=400, detail="Height must be between 256 and 2048")
    
    # Simulate processing time (proportional to steps)
    processing_time = min((request.steps or 50) * 0.05, 3.0)
    time.sleep(processing_time)
    
    # Generate placeholder image
    image_data = generate_placeholder_image(
        request.prompt,
        request.width,
        request.height
    )
    
    return Response(
        content=image_data,
        media_type="image/png",
        headers={
            "Content-Disposition": f"attachment; filename=generated_{int(time.time())}.png",
            "X-Seed": str(request.seed or random.randint(0, 999999))
        }
    )

@app.post("/v1/img2img")
async def image_to_image(request: ImageGenRequest):
    """Mock image-to-image endpoint"""
    # Same as generate for mock purposes
    return await generate_image(request)

@app.get("/v1/models")
async def list_models():
    """List available models"""
    return {
        "models": [
            {"id": "stable-diffusion-xl", "name": "Stable Diffusion XL"},
            {"id": "stable-diffusion-v2", "name": "Stable Diffusion v2"},
            {"id": "dall-e-3", "name": "DALL-E 3"}
        ]
    }

@app.get("/")
async def root():
    return {
        "service": "Mock Image Generation Service",
        "version": "1.0.0",
        "endpoints": ["/v1/generate", "/v1/img2img", "/v1/models"],
        "status": "operational"
    }
