
export const navigationItems = [
  { name: 'Home', path: '/' },
  { name: 'Documentation', path: '/documentation' },
  { name: 'Cookbook', path: '/cookbook' },
  { name: 'Deployment', path: '/deployment' },
  { name: 'Sandbox', path: '/sandbox' },
  { name: 'Readiness Hub', path: '/deployment-readiness' },
  { name: 'Devonn Chat', path: '/devonn-chat' },
  { name: 'Local AI', path: '/local-ai' },
  { name: 'Music Studio', path: '/music-studio' },
  { name: 'Devonn.TV', path: '/devonn-tv' },
  { name: 'Workflows', path: '/workflows' },
  { name: 'Legacy Workflows', path: '/legacy-workflows' },
  { name: 'MCP Catalog', path: '/mcp-catalog' },
  { name: 'MCP Management', path: '/mcp-management' },
  { name: 'API', path: '/api' },
  { name: 'Advanced AI', path: '/advanced-ai' },
  { name: 'About', path: '/about' },
];
